config/routes.rb
Homejet::Application.routes.draw do

  root to: 'application#index'

  # Camera
  get 'camera' => 'camera#index', as: 'cams'
  get 'camera/:id' => 'camera#show', as: 'cam'
  get 'new_camera' => 'camera#new', as: 'new_cam'
  post 'cameras' => 'camera#create', as: 'cameras'
  put 'cameras/:id' => 'camera#update', as: 'camera'
  get 'edit_camera/:id' => 'camera#edit', as: 'edit_cam'
  get 'remove_camera/:id' => 'camera#destroy', as: 'remove_cam'

  # Sensor
  get 'sensors' => 'sensors#index', as: 'sensors'
  get 'sensors/:id' => 'sensors#show', as: 'sensor'
  get 'new_sensor' => 'sensors#new', as: 'new_sensor'
  post 'sensors' => 'sensors#create', as: 'sensors'
  put 'sensors/:id' => 'sensors#update', as: 'sensor'
  get 'edit_sensor/:id' => 'sensors#edit', as: 'edit_sensor'
  get 'remove_sensor/:id' => 'sensors#destroy', as: 'remove_sensor'

  # Outlet
  get 'outlets' => 'outlets#index', as: 'outlets'
  get 'outlets/:id' => 'outlets#show', as: 'outlet'
  get 'new_outlet' => 'outlets#new', as: 'new_outlet'
  post 'outlets' => 'outlets#create', as: 'outlets'
  put 'outlets/:id' => 'outlets#update', as: 'outlet'
  get 'edit_outlet/:id' => 'outlets#edit', as: 'edit_outlet'
  get 'remove_outlet/:id' => 'outlets#destroy', as: 'remove_outlet'

  # Script
  get 'scripts' => 'scripts#index', as: 'scripts'
  get 'scripts/:id' => 'scripts#show', as: 'script'
  get 'new_script' => 'scripts#new', as: 'new_script'
  post 'scripts' => 'scripts#create', as: 'scripts'
  put 'scripts/:id' => 'scripts#update', as: 'script'
  get 'edit_script/:id' => 'scripts#edit', as: 'edit_script'
  get 'remove_script/:id' => 'scripts#destroy', as: 'remove_script'

  # Users
  get 'profile' => 'users#index', as: 'user'
  put 'profile' => 'users#update', as: 'user_put'
  get 'profile/phone' => 'users#phone', as: 'user_phone'
  put 'profile/phone' => 'users#phone_put', as: 'user_phone_put'
  put 'profile/linking' => 'users#linking_put', as: 'user_linking_put'
  get 'profile/unlinking' => 'users#unlinking', as: 'user_unlinking'
  get 'profile/secure' => 'users#secure', as: 'secure'
  get 'sms_authorization' => 'users#sms_authorization', as: 'sms_authorization'
  get 'register' => 'users#new', as: 'register'
  post 'register' => 'users#create', as: 'users'
  get 'logout' => 'users#logout', as: 'logout'
  get 'login' => 'users#login', as: 'login'
  post 'login' => 'users#create_session', as: 'create_session'
  post 'login_sms' => 'users#create_session_sms', as: 'create_session_sms'

  # Sender 
  post 'sender' => 'sender#index', as: 'sender'

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :name, :password, :password_confirmation, :surname, :phone, :linking_code, :phone_validate,
                  :sms_authorization, :sms_authorization_code

  has_many :cams, :class_name => "Camera", :foreign_key => "user_id"
  has_many :sensors, :class_name => "Sensor", :foreign_key => "user_id"
  has_many :outlets, :class_name => "Outlet", :foreign_key => "user_id"
  has_many :scripts, :class_name => "Script", :foreign_key => "user_id"

  validates :name, :email, :surname, :password, presence: true
  validates :email, :uniqueness => true
  validates :password, confirmation: true

  def full_name
    "#{self.name} #{self.surname}"
  end

end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController

  require 'net/http'
  require 'uri'

  before_filter :login?, :except => [:new, :create, :login, :sms_authorization, :create_session, :create_session_sms]
  before_filter :user_find, :except => [:new, :create, :login, :sms_authorization, :create_session, :create_session_sms]

  def update

    @err = true

    if @user.update_attributes(params[:user])
      @err = false
    end

    respond_to do |format|
      format.js
    end

  end

  def index
    @sidebar = 2
  end

  def secure
    @sidebar = 2
  end

  def phone
    @sidebar = 2
  end

  def unlinking
    @user.phone = ''
    @user.phone_validate = false
    @user.sms_authorization = false
    @user.save
    redirect_to user_phone_url
  end

  def linking_put

    if params[:linking_code] == @user.linking_code
      @user.linking_code = ''
      @user.phone_validate = true
      @user.save
    end

    respond_to do |format|
      format.js
    end

  end

  def phone_put

    @err = true

    if @user.update_attributes(params[:user])
      @user.linking_code = (0...5).map{ (0..9).to_a[rand(10)] }.join
      Net::HTTP.post_form URI.parse('http://api.smsfeedback.ru/messages/v2/send'), { :login => 'homejet', :password => 'Ynsgwmue5979HO', :phone => @user.phone, :text => "Код: #{@user.linking_code}", :sender => 'Homejet' }
      
      @user.save
      @err = false
    end

    respond_to do |format|
      format.js
    end
  end

  def new
    @user = User.new
    render 'new', layout: 'login'
  end

  def create
    @user = User.new(params[:user])
    @user.password = Digest::MD5.hexdigest(@user.password)
    @user.password_confirmation = Digest::MD5.hexdigest(@user.password_confirmation)
    if @user.save
      session[:user] = @user.id
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def login
    render 'login', layout: 'login'
  end

  def sms_authorization
    render 'sms_authorization', layout: 'login'
  end

  def create_session_sms
    @user = User.find(session[:sms_authorization_user])
    if params[:sms_authorization_code] == @user.sms_authorization_code
      session[:user] = @user.id
      session[:sms_authorization] = false
    end
    respond_to do |format|
      format.js
    end
  end

  def create_session
    @user = User.find_by_email(params[:email])
    if @user && @user.password == Digest::MD5.hexdigest(params[:password])
      unless @user.sms_authorization
        session[:user] = @user.id
      else
        session[:sms_authorization_user] = @user.id
        session[:sms_authorization] = true
        @user.sms_authorization_code = (0...5).map{ (0..9).to_a[rand(10)] }.join
        if !@user.phone.blank? && @user.phone_validate
          Net::HTTP.post_form URI.parse('http://api.smsfeedback.ru/messages/v2/send'), { :login => 'homejet', :password => 'Ynsgwmue5979HO', :phone => @user.phone, :text => "Код: #{@user.sms_authorization_code}", :sender => 'Homejet' }
        end
        @user.save
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def logout
    session[:user] = nil
    redirect_to root_url
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.js.erb
<% if login? %>

  location.href = '<%= root_url %>';

<% else %>

  $('p.error_description').remove();
  $('.user_form .error').removeClass('error');
  <% @user.errors.messages.each do |error| %>
    $('#user_<%= error[0] %>').addClass('error');
    $('<p class="error_description"><%= error[1][0] %></p>').insertAfter('#user_<%= error[0] %>');
  <% end %>

<% end %>

app/views/users/create_session.js.erb
<% if session[:sms_authorization] %>

  location.href = '<%= sms_authorization_url %>';

<% else %>

  $('#email').removeClass('error');
  $('#password').removeClass('error');
  $('p.error_description').remove();
  
  <% if login? %>
  
    location.href = '<%= root_url %>';
  
  <% else %>
  
    $('<p class="error_description">логин или пароль неверен</p>').insertAfter('#email');
    $('#email').addClass('error');
    $('#password').addClass('error');
  
  <% end %>

<% end %>

app/views/users/create_session_sms.js.erb
$('#sms_authorization_code').removeClass('error');
$('p.error_description').remove();

<% if login? %>

  location.href = '<%= root_url %>';

<% else %>

  $('<p class="error_description">код неверен</p>').insertAfter('#sms_authorization_code');
  $('#sms_authorization_code').addClass('error');

<% end %>

app/views/users/index.html.erb
<div class="menu">
  <a href="<%= user_url %>" class="btn btn_menu">Информация</a>
  <a href="<%= secure_url %>" class="btn btn_menu">Безопасность</a>
  <a href="<%= user_phone_url %>" class="btn btn_menu">Телефон</a>
</div>


<%= form_for @user, url: user_put_url, remote: true do |f| -%>
  
<div class="form form_settings">

  <!--<div class="form__field line">
    <div class="form__left"><label class="b-label">E-mail</label></div>
    <div class="form__right">
      <div class="b-input-i">
        <%= f.text_field :email, class: 'b-input' %>
      </div>
    </div>
  </div>-->

  <div class="form__field line">
    <div class="form__left"><label class="b-label">Имя</label></div>
    <div class="form__right">
      <div class="b-input-i">
        <%= f.text_field :name, class: 'b-input' %>
      </div>
    </div>
  </div>

  <div class="form__field line">
    <div class="form__left"><label class="b-label">Фамилия</label></div>
    <div class="form__right">
      <div class="b-input-i">
        <%= f.text_field :surname, class: 'b-input' %>
      </div>
    </div>
  </div>

  <div class="control__action">
    <%= f.submit "Сохранить изменения", class: 'btn btn_menu btn_green' %>
  </div>
</div>

<% end -%>

app/views/users/linking_put.js.erb
<% if @user.phone_validate %>

  location.href = '<%= user_phone_url %>'

<% else %>

  $('p.error_description').remove();
  $('.edit_user .error').removeClass('error');
  $('#user_linking_code').addClass('error');
  $('<p class="error_description">Код введен неверно</p>').insertAfter('#user_linking_code');

<% end %>

app/views/users/login.html.erb
<div class="container">
  <div class="login">
    <div class="login__head">Вход в Homejet</div>
    <div class="login__body">
      <div class="form form_login">
        <%= form_tag(create_session_url, remote: true) do %>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Логин</label>
            </div>
            <div class="form__right">
              <div class="b-input-i b-input-icon">
                <i class="ico ico_type_user"></i>
                <%= text_field_tag :email, '', class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Пароль</label>
            </div>
            <div class="form__right">
              <div class="b-input-i b-input-icon">
                <i class="ico ico_type_lock"></i>
                <%= password_field_tag :password, '', class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field form__field_action line">
            <div class="form__right">
              <label for="" class="b-label b-label-register"><%= link_to "Регистрация", register_url %></label>
              <%= submit_tag "Войти", class: 'btn btn_menu', disable_with: 'Logining...' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="login register">
    <div class="login__head">Регистрация в Homejet</div>
    <div class="login__body">
      <div class="form form_login user_form">
        <%= form_for(@user, remote: true, html: { class: 'user_form' }) do |f| %>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Имя</label>
            </div>
            <div class="form__right">
              <div class="b-input-i">
                <%= f.text_field :name, class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Фамилия</label>
            </div>
            <div class="form__right">
              <div class="b-input-i">
                <%= f.text_field :surname, class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Email</label>
            </div>
            <div class="form__right">
              <div class="b-input-i b-input-icon">
                <i class="ico ico_type_user"></i>
                <%= f.text_field :email, class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Пароль</label>
            </div>
            <div class="form__right">
              <div class="b-input-i b-input-icon">
                <i class="ico ico_type_lock"></i>
                <%= f.password_field :password, class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Ещё раз</label>
            </div>
            <div class="form__right">
              <div class="b-input-i">
                <%= f.password_field :password_confirmation, class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field form__field_action line">
            <div class="form__right">
              <label for="" class="b-label b-label-register"><%= link_to "Войти", login_url %></label>
              <%= f.submit "Зарегистрироваться", class: 'btn btn_menu', disable_with: 'Logining...' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/phone.html.erb
<div class="menu">
  <a href="<%= user_url %>" class="btn btn_menu">Информация</a>
  <a href="<%= secure_url %>" class="btn btn_menu">Безопасность</a>
  <a href="<%= user_phone_url %>" class="btn btn_menu">Телефон</a>
</div>

<!-- Телефон пуст, валидации нет -->
<% if !@user.phone_validate && @user.phone.blank? %>

  <%= form_for @user, url: user_phone_put_url, remote: true do |f| -%>
    
  <div class="form form_settings">
  
    <div class="form__field line">
      <div class="form__left"><label class="b-label">Телефон</label></div>
      <div class="form__right">
        <div class="b-input-i">
          <%= f.text_field :phone, class: 'b-input' %>
        </div>
      </div>
    </div>
  
    <div class="control__action">
      <%= f.submit "Привязать телефон", class: 'btn btn_menu btn_green' %>
    </div>
  </div>
  
  <% end -%>

<% end %>


<!-- Телефон заполнен, валидации нет -->
<% if !@user.phone_validate && !@user.phone.blank? %>

  <%= form_for @user, url: user_linking_put_url, remote: true do |f| -%>

  <div class="form form_settings">

    <div class="form__field line">
      <div class="form__left"><label class="b-label">Код в СМС</label></div>
      <div class="form__right">
        <div class="b-input-i">
          <input type="text" name="linking_code" class="b-input" id="user_linking_code">
        </div>
      </div>
    </div>

    <div class="control__action">
      <%= f.submit "Подтвердить", class: 'btn btn_menu btn_green' %> &nbsp; <a href="<%= user_unlinking_url %>" class="btn btn_menu btn_green">Другой телефон</a>
    </div>
  </div>

  <% end -%>

<% end %>


<!-- Телефон заполнен, валидация есть -->
<% if @user.phone_validate && !@user.phone.blank? %>

  <p>Телефон привязан: <%= @user.phone %></p>

  <br /><br />

  <div class="control__action">
    <a href="<%= user_unlinking_url %>" class="btn btn_menu btn_green">Отвязать</a>
  </div>

<% end %>

app/views/users/phone_put.js.erb
<% if @err %>

  $('p.error_description').remove();
  $('.edit_user .error').removeClass('error');
  <% @user.errors.messages.each do |error| %>
    $('#user_<%= error[0] %>').addClass('error');
    $('<p class="error_description"><%= error[1][0] %></p>').insertAfter('#user_<%= error[0] %>');
  <% end %>

<% else %>

  location.href = '<%= user_phone_put_url %>';

<% end %>

app/views/users/secure.html.erb
<div class="menu">
  <a href="<%= user_url %>" class="btn btn_menu">Информация</a>
  <a href="<%= secure_url %>" class="btn btn_menu">Безопасность</a>
  <a href="<%= user_phone_url %>" class="btn btn_menu">Телефон</a>
</div>


<%= form_for @user, url: user_put_url, remote: true do |f| -%>

<div class="form form_settings">

  <% if !@user.phone.blank? && @user.phone_validate %>

  <div class="form__field line">
    <div class="form__left"><label class="b-label">SMS авторизация</label></div>
    <div class="form__right">
      <div class="b-input-i">
        <%= f.check_box :sms_authorization %>
      </div>
    </div>
  </div>

  <% end %>


  <div class="control__action">
    <%= f.submit "Сохранить изменения", class: 'btn btn_menu btn_green' %>
  </div>
</div>

<% end -%>

app/views/users/sms_authorization.html.erb
<div class="container">
  <div class="login">
    <div class="login__head">Вход в Homejet</div>
    <div class="login__body">
      <div class="form form_login">
        <%= form_tag(create_session_sms_url, remote: true) do %>
          <div class="form__field line">
            <div class="form__left">
              <label class="b-label">Код автор.</label>
            </div>
            <div class="form__right">
              <div class="b-input-i">
                <%= text_field_tag :sms_authorization_code, '', class: 'b-input' %>
              </div>
            </div>
          </div>
          <div class="form__field form__field_action line">
            <div class="form__right">
              <%= submit_tag "Войти", class: 'btn btn_menu', disable_with: 'Logining...' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/update.js.erb
<% if @err %>

  $('p.error_description').remove();
  $('.edit_user .error').removeClass('error');
  <% @user.errors.messages.each do |error| %>
    $('#user_<%= error[0] %>').addClass('error');
    $('<p class="error_description"><%= error[1][0] %></p>').insertAfter('#user_<%= error[0] %>');
  <% end %>

<% else %>

  location.href = '<%= user_url %>';

<% end %>