config/routes.rb
Homejet::Application.routes.draw do

  root to: 'application#index'

  # Camera
  get 'camera' => 'camera#index', as: 'cams'
  get 'camera/:id' => 'camera#show', as: 'cam'
  get 'new_camera' => 'camera#new', as: 'new_cam'
  post 'cameras' => 'camera#create', as: 'cameras'
  put 'cameras/:id' => 'camera#update', as: 'camera'
  get 'edit_camera/:id' => 'camera#edit', as: 'edit_cam'
  get 'remove_camera/:id' => 'camera#destroy', as: 'remove_cam'

  # Sensor
  get 'sensors' => 'sensors#index', as: 'sensors'
  get 'sensors/:id' => 'sensors#show', as: 'sensor'
  get 'new_sensor' => 'sensors#new', as: 'new_sensor'
  post 'sensors' => 'sensors#create', as: 'sensors'
  put 'sensors/:id' => 'sensors#update', as: 'sensor'
  get 'edit_sensor/:id' => 'sensors#edit', as: 'edit_sensor'
  get 'remove_sensor/:id' => 'sensors#destroy', as: 'remove_sensor'

  # Outlet
  get 'outlets' => 'outlets#index', as: 'outlets'
  get 'outlets/:id' => 'outlets#show', as: 'outlet'
  get 'new_outlet' => 'outlets#new', as: 'new_outlet'
  post 'outlets' => 'outlets#create', as: 'outlets'
  put 'outlets/:id' => 'outlets#update', as: 'outlet'
  get 'edit_outlet/:id' => 'outlets#edit', as: 'edit_outlet'
  get 'remove_outlet/:id' => 'outlets#destroy', as: 'remove_outlet'

  # Script
  get 'scripts' => 'scripts#index', as: 'scripts'
  get 'scripts/:id' => 'scripts#show', as: 'script'
  get 'new_script' => 'scripts#new', as: 'new_script'
  post 'scripts' => 'scripts#create', as: 'scripts'
  put 'scripts/:id' => 'scripts#update', as: 'script'
  get 'edit_script/:id' => 'scripts#edit', as: 'edit_script'
  get 'remove_script/:id' => 'scripts#destroy', as: 'remove_script'

  # Users
  get 'profile' => 'users#index', as: 'user'
  put 'profile' => 'users#update', as: 'user_put'
  get 'profile/phone' => 'users#phone', as: 'user_phone'
  put 'profile/phone' => 'users#phone_put', as: 'user_phone_put'
  put 'profile/linking' => 'users#linking_put', as: 'user_linking_put'
  get 'profile/unlinking' => 'users#unlinking', as: 'user_unlinking'
  get 'profile/secure' => 'users#secure', as: 'secure'
  get 'sms_authorization' => 'users#sms_authorization', as: 'sms_authorization'
  get 'register' => 'users#new', as: 'register'
  post 'register' => 'users#create', as: 'users'
  get 'logout' => 'users#logout', as: 'logout'
  get 'login' => 'users#login', as: 'login'
  post 'login' => 'users#create_session', as: 'create_session'
  post 'login_sms' => 'users#create_session_sms', as: 'create_session_sms'

  # Sender 
  post 'sender' => 'sender#index', as: 'sender'

end

app/views/layouts/_foot.html.erb
</body>
</html>

app/views/layouts/_footer.html.erb
<div class="ftr">
  <div class="case">
    <div class="case__inner">
      <div class="ftr__menu">
        <a class="b-link b-link_ftr" href="#">О проекте</a>
        <a class="b-link b-link_ftr" href="#">Вопросы и ответы</a>
        <a class="b-link b-link_ftr" href="#">Условия использования</a>
        <a class="b-link b-link_ftr" href="#">Конфиденциальность </a>
        <a class="b-link b-link_ftr" href="#">Телефоны и адреса</a>
      </div>
      <div class="ftr__social">
        <a class="b-link" href="#"><i class="ico ico_type_fb"></i></a>
        <a class="b-link" href="#"><i class="ico ico_type_vk"></i></a>
        <a class="b-link" href="#"><i class="ico ico_type_tw"></i></a>
      </div>
      <div class="ftr__company">
        © 2012-2013 ООО «ХоумДжет». Все права защищены
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title></title>
  <%= stylesheet_link_tag "application" %>
  <!--[if lt IE 8]><link rel="stylesheet" href="/assets/style.ie.css" /><![endif]-->
  <!--[if lt IE 7]><script type="text/javascript" src="/assets/pngfix.js"></script><![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

app/views/layouts/_header.html.erb
<div class="hdr">
  <div class="case line">
    <div class="case__inner line">
      <div class="logo">
        <a href="/"><img src="/assets/logo.png" alt=""></a>
      </div>
      <div class="account">
        <div class="account__name">
          <div class="account__name-foto"><a href="<%= user_url %>"><img src="/assets/user.png" alt=""></a></div>
          <a class="account__name-text" href="<%= user_url %>"><%= @user.full_name %></a>
        </div>
        <div class="account__exit">
          <a class="account__name-text" href="<%= logout_url %>"><i class="ico ico_type_exit"></i></a>
          <%= link_to "Выйти", logout_url, class: 'account__name-text' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="main__sidebar">
  <% active = (request.url == root_url) %>
  <div class="main__sidebar-block main__sidebar-block-fst <%= 'main__sidebar-active-black' if active  %>">
    <a class="main__sidebar-link" href="<%= root_url %>"><i class="ico ico_type_review"></i><span class="main__sidebar-text">Обзор</span></a>
  </div>
  <% active = (request.url == cams_url) || (request.url == new_cam_url) %>
  <% if @camera && !@camera.id.blank? %>
    <% active = (request.url == edit_cam_url(@camera.id)) || (request.url == cam_url(@camera.id)) %>
  <% end %>
  <div class="main__sidebar-block <%= 'main__sidebar-active-black' if active  %>">
    <a class="main__sidebar-link" href="<%= cams_url %>"><i class="ico ico_type_camera"></i><span class="main__sidebar-text">Камеры</span></a>
  </div>
  <% active = (request.url == sensors_url) || (request.url == new_sensor_url) %>
  <% if @sensor && !@sensor.id.blank? %>
    <% active = (request.url == edit_sensor_url(@sensor.id)) || (request.url == sensor_url(@sensor.id)) %>
  <% end %>
  <div class="main__sidebar-block <%= 'main__sidebar-active-black' if active  %>">
    <a class="main__sidebar-link" href="<%= sensors_url %>"><i class="ico ico_type_temp"></i><span class="main__sidebar-text">Температура</span></a>
  </div>
  <% active = (request.url == outlets_url) || (request.url == new_outlet_url) %>
  <% if @outlet && !@outlet.id.blank? %>
    <% active = (request.url == edit_outlet_url(@outlet.id)) || (request.url == outlet_url(@outlet.id)) %>
  <% end %>
  <div class="main__sidebar-block <%= 'main__sidebar-active-black' if active  %>">
    <a class="main__sidebar-link" href="<%= outlets_url %>"><i class="ico ico_type_power"></i><span class="main__sidebar-text">Питание</span></a>
  </div>
  <% active = (request.url == scripts_url) || (request.url == new_script_url) %>
  <% if @script && !@script.id.blank? %>
    <% active = (request.url == edit_script_url(@script.id)) || (request.url == script_url(@script.id)) %>
  <% end %>
  <div class="main__sidebar-block <%= 'main__sidebar-active-black' if active  %>">
    <a class="main__sidebar-link" href="<%= scripts_url %>"><i class="ico ico_type_script"></i><span class="main__sidebar-text">Сценарии</span></a>
  </div>
  <% active = (request.url == user_url) || (request.url == user_phone_url) || (request.url == secure_url) %>
  <div class="main__sidebar-block main__sidebar-block-lst <%= 'main__sidebar-active-black' if active  %>">
    <a class="main__sidebar-link" href="<%= user_url %>"><i class="ico ico_type_settings"></i><span class="main__sidebar-text">Настройки</span></a>
  </div>
</div>

app/views/layouts/_sidebar1.html.erb
<div class="main__list">
  <a class="list-link list-link_top list-link_bold" href="<%= root_url %>">Главная</a>
</div>
<div class="main__list-bg">

</div>

app/views/layouts/_sidebar2.html.erb
<div class="main__list">
  <a class="list-link list-link_top list-link_bold">Настройки</a>
  <% active = (request.url == user_url) || (request.url == secure_url) || (request.url == user_phone_url) %>
  <a class="list-link list-link_accord<%= '-active' if active %>" href="<%= user_url %>">Учётная запись</a>
</div>
<div class="main__list-bg">

</div>

app/views/layouts/_sidebar3.html.erb
<div class="main__list">
  <a class="list-link list-link_top list-link_bold">Видеонаблюдение</a>
  <% cams = @user.cams %>
  <% cams.each do |cam| %>
    <% if @camera && !@camera.id.blank? %>
      <% active = (request.url == cam_url(cam)) || (request.url == edit_cam_url(cam)) %>
    <% end %>
    <a class="list-link list-link_accord <%= 'list-link_accord-active' if active %>" href="<%= cam_url(cam) %>"><%= cam.name %><i class="ico ico_type_round"></i></a>
  <% end %>
  <% active = (request.url == new_cam_url) %>
  <a class="list-link list-link_accord<%= '-active' if active %>" href="<%= new_cam_url %>">Добавление новой камеры</a>
</div>
<div class="main__list-bg">

</div>

app/views/layouts/_sidebar4.html.erb
<div class="main__list">
  <a class="list-link list-link_top list-link_bold">Температура</a>
  <% sensors = @user.sensors %>
  <% sensors.each do |sensor| %>
    <% if @sensor && !@sensor.id.blank? %>
      <% active = (request.url == sensor_url(sensor)) || (request.url == edit_sensor_url(sensor)) %>
    <% end %>
    <a class="list-link list-link_accord <%= 'list-link_accord-active' if active %>" href="<%= sensor_url(sensor) %>"><%= sensor.name %><i class="ico ico_type_round"></i></a>
  <% end %>
  <% active = (request.url == new_sensor_url) %>
  <a class="list-link list-link_accord<%= '-active' if active %>" href="<%= new_sensor_url %>">Добавление нового датчика</a>
</div>
<div class="main__list-bg">

</div>

app/views/layouts/_sidebar5.html.erb
<div class="main__list">
  <a class="list-link list-link_top list-link_bold">Розетки</a>
  <% outlets = @user.outlets %>
  <% outlets.each do |outlet| %>
    <% if @outlet && !@outlet.id.blank? %>
      <% active = (request.url == outlet_url(outlet)) || (request.url == edit_outlet_url(outlet)) %>
    <% end %>
    <a class="list-link list-link_accord <%= 'list-link_accord-active' if active %>" href="<%= outlet_url(outlet) %>"><%= outlet.name %><% if outlet.state %><i class="ico ico_type_round"></i><% end %></a>
  <% end %>
  <% active = (request.url == new_outlet_url) %>
  <a class="list-link list-link_accord<%= '-active' if active %>" href="<%= new_outlet_url %>">Добавление новой розетки</a>
</div>
<div class="main__list-bg">

</div>

app/views/layouts/_sidebar6.html.erb
<div class="main__list">
  <a class="list-link list-link_top list-link_bold">Сценарии</a>
  <% scripts = @user.scripts %>
  <% scripts.each do |script| %>
    <% if @script && !@script.id.blank? %>
      <% active = (request.url == script_url(script)) || (request.url == edit_script_url(script)) %>
    <% end %>
    <a class="list-link list-link_accord <%= 'list-link_accord-active' if active %>" href="<%= script_url(script) %>"><%= script.name %></a>
  <% end %>
  <% active = (request.url == new_script_url) %>
  <a class="list-link list-link_accord<%= '-active' if active %>" href="<%= new_script_url %>">Добавление нового сценария</a>
</div>
<div class="main__list-bg">

</div>

app/views/layouts/application.html.erb
<%= render :partial => 'layouts/head' %>

<div class="container">

  <%= render :partial => 'layouts/header' %>

  <div class="cnt">
    <div class="case">
      <div class="case__inner line">
         <div class="main line">

           <%= render :partial => 'layouts/sidebar' %>

           <%= render :partial => "layouts/sidebar#{@sidebar}" %>

           <div class="main__block">
             <div class="main__block-inside">
              <%= yield %>
             </div>
           </div>

         </div>
      </div>
    </div>
  </div>

</div>

<%= render :partial => 'layouts/foot' %>

app/views/layouts/login.html.erb
<%= render :partial => 'layouts/head' %>

<%= yield %>

<%= render :partial => 'layouts/foot' %>